FROM odbrg6/olga:slim-buster

RUN git clone https://github.com/odbrg6/olga.git /root/sbb_b
WORKDIR /root/sbb_b
RUN apk add --update --no-cache p7zip
RUN pip3 install --no-cache-dir -r requirements.txt
ENV PATH="/home/sbb_b/bin:$PATH"

CMD ["python3", "-m", "sbb_b"]
